image:
  file: utils/dockerfiles/gitpod-base.Dockerfile

## Example is handled separately in GitPod for faster initialization.
tasks:
  - name: Setup LF
    init: |
      bash ./utils/scripts/setup-lf.bash $RELEASE_BUILD
      gp sync-done setup-lf
    command: exit
  - name: Setup Example
    init: git clone https://github.com/lf-lang/examples-lingua-franca.git examples --branch main
    command: exit
  - name: Setup Java and node.js for user
    init: |
      bash -i ./utils/scripts/setup-user-env.bash
      gp sync-done setup-user-env
    command: exit
## Dirty hack, https://github.com/gitpod-io/gitpod/issues/9275#issuecomment-1098275529
  - name: Setup env
    before: >
      printf 'export PATH="%s:$PATH"; export LF_PATH="%s";\n' "${GITPOD_REPO_ROOT}/lingua-franca/bin" "${GITPOD_REPO_ROOT}/lingua-franca/" >> $HOME/.bashrc && exit
  - name: Notificaton
    command: |
      echo -e "\033[0;31mPlease wait while GitPod executes some finishing touch...... \033[0m"
      gp sync-await setup-lf
      gp sync-await setup-user-env
      \. ~/.bashrc
      echo "Enjoy!"


vscode: 
  extensions:
    - lf-lang.vscode-lingua-franca
    - kieler.klighd-vscode
